### PR TITLE
Update Developer Guide's user stories and use cases

### PR DESCRIPTION
**Pull request by felissaf**

### CODE REVIEW

**Review by charliemoweng — COMMENTED** [review]
I think the case of deleting a student and deleting a student from a module should be the same one right? I don't think we have a standalone delete student method, do we?

**Comment by Ruofan1023** [comment]
> I think the case of deleting a student and deleting a student from a module should be the same one right? I don't think we have a standalone delete student method, do we?

Currently, we can create a standalone student first then add it to the module. So removing the student from a module does not delete the student completely?

**Comment by felissaf** [comment]
Yes I think it's not supposed to delete the student if you remove the student from a module

**Comment by WangGLJoseph** [comment]
LGTM! I agree that removing a student from a module should be kept separate from deleting the student completely, though functionality for deleting the student is not in v1.2.

**Pull request merged**
