### PR TITLE
Branch ruofan update uml

### PR DESCRIPTION
**Pull request by Ruofan1023**
Update UML and correct some issues in DG

- Include UML diagrams for design and implementation
- Correct date format to YYYY-MM-DD
- Update explanation for some implementations
- Update Github pages layout width so that images have more space (hence larger for view)

### CODE REVIEW

**Comment by Ruofan1023** [comment]
> what a mad lad. thanks for all these efforts. 🚀 

Hahaha do look thru the diagrams if possible in case that I missed something!

**Review by tanjoewel — COMMENTED** [review]
I looked through the pictures and they look good n accurate! Amazing job :>

**Comment by WangGLJoseph** [comment]
Amazing work! Found some minor issues, can't seem to comment on the image files directly so I'll put them here

**Comment by WangGLJoseph** [comment]
Screenshot 2021-11-03 at 2 02 59 PM
Screenshot 2021-11-03 at 2 03 36 PM

There seems to be some inconsistency between the AddModuleSequenceDiagram1 and the AddStudentSequenceDIagram1

**Comment by Ruofan1023** [comment]
Thanks for pointing this out! I think for AddModuleCommandParser the activation bar should not touch the class name box, and should follow that in the add student sequence diagram right?

**Comment by felissaf** [comment]
Amazing:') Thanks Ruofan!!!!🥳👍🏻

**Pull request merged**
