### PR TITLE
Update Joe Wel's part of AboutUs.md

### PR DESCRIPTION
**Pull request by tanjoewel**
Update Joe Wel's part of AboutUs.md

### CODE REVIEW

**Comment by WangGLJoseph** [comment]
LGTM!

**Comment by Ruofan1023** [comment]
LGTM!

**Comment by Ruofan1023** [comment]
LGTM

**Comment by Ruofan1023** [comment]
Oh I just realised the image name should be your lowercase github name to be detected properly, as explained [here](https://nus-cs2103-ay2122s1.github.io/website/schedule/week7/project.html).

> The filename of the profile photo should be docs/images/githbub_username_in_lower_case.png
Note the need for lower case (why lowercase?) e.g. JohnDoe123 -> docs/images/johndoe123.png not docs/images/JohnDoe123.png.

**Pull request merged**
