### PR TITLE
Branch ruofan update developer guide

### PR DESCRIPTION
**Pull request by Ruofan1023**
If there's no issue, this will be the DG pdf that we will gonna submit. Please take a look. If there's any issue I will update and upload a new version for yall to check!
[Developer Guide.pdf](https://github.com/AY2122S1-CS2103-F09-1/tp/files/7502798/Developer.Guide.pdf)

### CODE REVIEW

**Comment by WangGLJoseph** [comment]
LGTM!

**Review by charliemoweng — COMMENTED** [review]
Maybe you can add a line breaker at the end of the current DG. so when I add in the Effort section it will be on its own page.

**Comment by Ruofan1023** [comment]
> Maybe you can add a line breaker at the end of the current DG. so when I add in the Effort section it will be on its own page.

ok!

**Comment by charliemoweng** [comment]
LGTM! I think can merge already. I'll pull and update it with the `Effort` section and we will be done.

**Pull request merged**
