### PR TITLE
Add skeleton of UniqueModuleList for operations on Modules

### PR DESCRIPTION
**Pull request by WangGLJoseph**
Also remove the y/ prefix in favor of treating the command type as a separate word, instead of a prefixed token.

### CODE REVIEW

**Comment by felissaf** [comment]
LGTM

**Comment by charliemoweng** [comment]
LGTM

**Review by Ruofan1023 — COMMENTED** [review]
Please also helps add in an attribute of uniqueModuleList here so the rest don't need to add in themselves and causing potential merge conflicts! Thank you!

**Comment by WangGLJoseph** [comment]
The latest commits adds the attributes and methods relating to Module operations within the TAB class, good catch @Ruofan1023 👍

**Comment by Ruofan1023** [comment]
LGTM!

**Pull request merged**
